db:
  type: postgres
  host: dpg-d1q3jaidbo4c73c3vasg-a.oregon-postgres.render.com
  port: 5432
  user: {{ env.DB_USER }}
  pass: {{ env.DB_PASS }}
  db:   {{ env.DB_NAME }}
  ssl: true

bindIP: 0.0.0.0
logLevel: info
dataPath: ./data
