db:
  type: postgres
  host: dpg-d1q3jaidbo4c73c3vasg-a.oregon-postgres.render.com
  port: 5432
  user: juggleease
  pass: 0ZY2rh1tD45MjKuIwrzy60p8MzCCJDDH
  db:   wikijs_db_oo8p
  ssl: true

bindIP: 0.0.0.0
logLevel: info
dataPath: ./data
